---
- name: copy panda pictures app
  copy: src=panda-pictures-app dest=/tmp/ owner=root group=root mode=0755 # TODO - restart on change..

- name: npm install
  npm: path=/tmp/panda-pictures-app

- name: Start panda-pictures
  command: forever start /tmp/panda-pictures-app/panda-pictures.js
  when: "forever_list.stdout.find('/tmp/panda-pictures-app/panda-pictures.js') == -1"
